import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StoreProvider from '@/lib/redux/storeProvider';
import { LangContextProvider } from '@/lib/context/langContext';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import AuthWrapper from '@/components/authWrapper/AuthWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GraphiQL App',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <LangContextProvider>
            <AuthWrapper>
              <Header />
              {children}
              <Footer />
            </AuthWrapper>
          </LangContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
