import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import './globals.css';
import StoreProvider from './storeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GraphiQL App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <StoreProvider>
          <Header />
          {children}
          <Footer />{' '}
        </StoreProvider>
      </body>
    </html>
  );
}
